version: 2.1

references:
  - &CERT_KEY certs-cache-{{ checksum "certs_cache_key" }}-v3

# this allows you to use CircleCI's dynamic configuration feature
setup: true

filters: &all_tags
  tags:
    only: /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.2.0

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - maybe_build_certs
      - run: # run a command
          name: Generate config
          command: |
            tools/circle-generate-config.sh generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml # use newly generated config to continue

commands:
  maybe_build_certs:
    steps:
      - run:
          name: Prepare cache key
          command: tools/make-certs-cache-key.sh > certs_cache_key && cat certs_cache_key
      - restore_cache:
          name: Restore certificates
          key: *CERT_KEY
      - run:
          # We do not rebuild certificates to ensure that the cached version
          # is the master-copy
          name: Build certificates if not cached
          command: test -f tools/ssl/mongooseim/key.pem || make certs
      - run:
          name: Print cert hashes for debugging
          command: find tools/ssl -type f -exec md5sum {} \; | sort
      - run:
          name: Continue if certificate exists
          command: test -f tools/ssl/mongooseim/key.pem
      - save_cache:
          name: Cache built certs
          key: *CERT_KEY
          paths:
            - ~/project/tools/ssl/ca
            - ~/project/tools/ssl/ca-clients
            - ~/project/tools/ssl/mongooseim

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup:
          filters: *all_tags

#testing
#testing1.1
#testing1.2
